const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
  isElectron: true,
  setIgnoreMouseEvents: (ignore) => ipcRenderer.send('set-ignore-mouse-events', ignore),
  enterChatMode: () => ipcRenderer.send('enter-chat-mode'),
  exitChatMode:  () => ipcRenderer.send('exit-chat-mode'),
  logout:        () => ipcRenderer.send('logout'),
  writeClipboard:(text) => ipcRenderer.send('write-clipboard', text),
  notifyNbarState:(visible) => ipcRenderer.send('nbar-state', visible),
  onFocusChatInput: (cb) => ipcRenderer.on('focus-chat-input', cb),
  onKeyInput:       (cb) => ipcRenderer.on('key-input', (_, p) => cb(p)),
  onAuthToken:      (cb) => ipcRenderer.on('auth-token', (_, d) => cb(d)),
  onWidgetToggle:   (cb) => ipcRenderer.on('widget-toggle', (_, d) => cb(d)),
  onNbarToggle:     (cb) => ipcRenderer.on('nbar-toggle', (_, v) => cb(v)),
  onPasteText:      (cb) => ipcRenderer.on('paste-text',  (_, text) => cb(text)),
  onPasteImage:     (cb) => ipcRenderer.on('paste-image', (_, b64)  => cb(b64)),
  onToggleLang:     (cb) => ipcRenderer.on('toggle-lang', cb),
  openExternal:     (url) => ipcRenderer.send('open-external', url),
  openImage:        (url) => ipcRenderer.send('open-image', url),
  openGameWindow: (tableId, token, srv) => ipcRenderer.send('open-game-window', tableId, token, srv),
  onGameWindowClosed: (cb) => ipcRenderer.on('game-window-closed', (_, tableId) => cb(tableId)),
  getOverlayVersion: () => ipcRenderer.sendSync('overlay-get-version'),
  getExeVersion: () => ipcRenderer.sendSync('exe-get-version'),
  applyOverlayUpdate: () => ipcRenderer.send('overlay-apply-update'),
  onOverlayUpdateAvailable: (cb) => ipcRenderer.on('overlay-update-available', (_, d) => cb(d)),
  applyExeUpdate: () => ipcRenderer.send('exe-apply-update'),
  onExeUpdateAvailable: (cb) => ipcRenderer.on('exe-update-available', (_, d) => cb(d)),
  onExeDownloadProgress: (cb) => ipcRenderer.on('exe-download-progress', (_, d) => cb(d)),
})
